
import java.util.Date;
import static javax.management.Query.gt;
import javax.swing.DefaultListModel;
import pm2_s3_e6.hip.SINHVIEN;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hip_1
 */
public class SINHVIEN_UI extends javax.swing.JFrame {

    /**
     * Creates new form SINHVIEN_UI
     */
    public SINHVIEN_UI() {
        initComponents();
        setEnable(false);        
        //setOption(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_masv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        rb_nam = new javax.swing.JRadioButton();
        rb_nu = new javax.swing.JRadioButton();
        txt_ma = new javax.swing.JTextField();
        txt_ht = new javax.swing.JTextField();
        txt_ns = new javax.swing.JTextField();
        txt_dc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_msv = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        bt_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_masv.setText("Mã sinh viên ");

        jLabel2.setText("Họ và tên ");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Địa chỉ");

        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_edit.setText("Edit");

        rb_nam.setText("Nam");
        rb_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_namActionPerformed(evt);
            }
        });

        rb_nu.setText("Nữ");
        rb_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nuActionPerformed(evt);
            }
        });

        list_msv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_msvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_msv);

        jLabel1.setText("Danh sách mã sinh viên");

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jlb_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(33, 33, 33)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ns)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rb_nam)
                                        .addGap(34, 34, 34)
                                        .addComponent(rb_nu)
                                        .addGap(45, 45, 45))
                                    .addComponent(txt_ht, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_dc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txt_ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_nam)
                                    .addComponent(rb_nu)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlb_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_edit)
                    .addComponent(bt_add)
                    .addComponent(bt_delete))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        if(bt_add.getText().equals("Add"))// equals là hàm so sánh tương tự như dấu so sánh "=="
        {
            //setNull();
             setEnable(true);
             bt_add.setText("Save");     // nên làm nút add như vậy để không phải làm thêm nút lưu 
             
             addListMasv();
             setNull();
             
        }  
        else{
            setEnable(true);
            bt_add.setText("Add");
            
            addListMasv();
            setNull();
        }       
        
        
    }//GEN-LAST:event_bt_addActionPerformed

    private void rb_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_namActionPerformed
        // TODO add your handling code here:
       // setOption(true);
    }//GEN-LAST:event_rb_namActionPerformed

    private void rb_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nuActionPerformed
        // TODO add your handling code here:
        //setOption(false);
    }//GEN-LAST:event_rb_nuActionPerformed

    private void list_msvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_msvMouseClicked
        // TODO add your handling code here:
        for(int i=0;i<k;i++){
            if(list_msv.getSelectedValue().equals(dssv[i].getMa())){
                txt_ma.setText(dssv[i].getMa());
                txt_ht.setText(dssv[i].getHt());
                txt_ns.setText(dssv[i].getNs()+" ");
                txt_dc.setText(dssv[i].getDc());
                
            }
        }        
    }//GEN-LAST:event_list_msvMouseClicked

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<k;i++){
            if(list_msv.getSelectedValue().equals(dssv[i].getMa()))
                //dssv[i].getMa().isEmpty();
                list_msv.remove(0);//remove(Integer.parseInt(dssv[i].getMa()));//nút xóa đang lỗi !
            }
    }//GEN-LAST:event_bt_deleteActionPerformed

    
    SINHVIEN dssv[]=new SINHVIEN[100];// khai báo mảng lưu danh sách sinh viên 
    int k=0; // biến biểu thị số sinh viên 
    DefaultListModel model =new DefaultListModel();
    boolean gt=true;
    
    public void addListMasv(){// thêm danh sách sinh viên vào list 
        InsertArray(k);
        model.addElement(dssv[k].getMa());
        list_msv.setModel(model); k++;       
    }      
    
     public void InsertArray(int k){// chèn dữ liệu vào mảng để in ra list_masv
         String ma=txt_ma.getText();
         String ht=txt_ht.getText();
         String dc=txt_dc.getText();
         boolean gt=true;
         if(rb_nam.isSelected()) gt=true;
         if(rb_nu.isSelected()) gt=false;
         //boolean gt=rb_nam.isEnabled();
         Date ns=new Date();
         SINHVIEN sv=new SINHVIEN(ma,ht,gt,ns,dc);
         dssv[k]=sv;         
     }// thêm danh sách sinh viên vào mảng 
     public void setNull(){
         txt_ma.setText("");
         txt_ht.setText("");
         txt_dc.setText("");
         txt_ns.setText("");        
}     // làm danh rỗng các textfiel 
     public void setEnable(boolean gt){
         txt_ma.setEnabled(gt);
         txt_ht.setEnabled(gt);
         txt_ns.setEnabled(gt);
         txt_dc.setEnabled(gt);
         rb_nam.setEnabled(gt);
         rb_nu.setEnabled(gt);                 
     } // làm mờ các nút 
    /* public void setOption(boolean gt){
         if(rb_nam.setSelected(gt));
         if(rb_nu.setSelected(!this.gt);
     }*/
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SINHVIEN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SINHVIEN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SINHVIEN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SINHVIEN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SINHVIEN_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb_masv;
    private javax.swing.JList<String> list_msv;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTextField txt_dc;
    private javax.swing.JTextField txt_ht;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ns;
    // End of variables declaration//GEN-END:variables
}
